# Generated by Django 5.2.14 on 2026-05-15 16:38

#import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_merge_20260515_0022'),
    ]

    operations = [
    migrations.AddField(
        model_name='appointment',
        name='comments',
        field=models.TextField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name='appointment',
        name='diagnosis',
        field=models.TextField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name='appointment',
        name='prescription',
        field=models.TextField(blank=True, null=True),
    ),
]
